name: Go

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Go 1.23.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: Display Go version
        run: go version
